# Generated by Django 3.0.3 on 2020-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_open_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, default='null')),
                ('ip', models.TextField(blank=True, default='null')),
                ('time', models.TextField(blank=True, default='null')),
            ],
        ),
    ]
