# Generated by Django 2.2.7 on 2019-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_questions',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='example_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='lang',
            field=models.CharField(blank=True, default='java', max_length=255),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='pbm_stmt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='test_input1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='test_input2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='test_input3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='code_questions',
            name='test_input4',
            field=models.TextField(blank=True),
        ),
    ]
