# Generated by Django 2.2.7 on 2019-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_auto_20191107_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
