# Generated by Django 2.2.7 on 2019-11-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_auto_20191108_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_questions',
            name='expected_output1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='code_questions',
            name='expected_output2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='code_questions',
            name='expected_output3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='code_questions',
            name='expected_output4',
            field=models.TextField(blank=True),
        ),
    ]
