# Generated by Django 3.0.5 on 2021-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_users_email_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_sent_status',
            field=models.IntegerField(default=0),
        ),
    ]
