# Generated by Django 2.2.7 on 2019-11-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_auto_20191109_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
