# Generated by Django 3.0.5 on 2021-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_auto_20210616_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_sent_iterations',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
