# Generated by Django 2.2.7 on 2019-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_admin_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_users',
            name='super_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
