# Generated by Django 2.2.7 on 2019-11-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_auto_20191113_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_users',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
