from django.urls import re_path
from smart import views

 
urlpatterns = [ 
    re_path(r'^signup/$', views.user_signup),
    re_path(r'^login/$', views.user_login),
    re_path(r'^test_code/$', views.ver_code_que),
    re_path(r'^test/$', views.get_login_status),
    re_path(r'^admin_status/$', views.get_admin_status),
    re_path(r'^sess/$', views.set_sess),
    re_path(r'^del/$', views.del_sess),
    re_path(r'^addcat/$', views.addcat),
    re_path(r'^get_code_count/$', views.get_code_count),
    re_path(r'^addque/$', views.addque),
    re_path(r'^addexam/$', views.add_exam),
    re_path(r'^rem_exam_dur/$', views.remaining_exam_duration),
    re_path(r'^addset/$', views.add_que_set),
    re_path(r'^add_code_que_set/$', views.add_code_que_set),
    re_path(r'^addcode/$', views.addcode),
    re_path(r'^setexam/$', views.set_cur_exam),
    re_path(r'^getcat/$', views.get_cat),
    re_path(r'^getexam/$', views.get_exam),
    re_path(r'^que/$', views.get_q),
    re_path(r'^ver/$', views.ver_q),
    re_path(r'^exam_logout/$', views.exam_logout),
    re_path(r'^code_exam_logout/$', views.code_exam_logout),
    re_path(r'^code_exam_status/$', views.code_exam_status),
    re_path(r'^get_code_que/$', views.get_code_que),
    re_path(r'^submit_code/$', views.submit_code),
    re_path(r'^feedback/$', views.feedback),
    re_path(r'^count_malpractices/$', views.count_malpractices),
    re_path(r'^exam_status/$', views.exam_status),
    re_path(r'^view_res/$', views.view_res),
    re_path(r'^view_code_res/$', views.view_code_res),
    re_path(r'^view_det_res/$', views.view_det_res),
    re_path(r'^view_res_user/$', views.view_res_user),
    re_path(r'^view_graph/$', views.view_graph),
    re_path(r'^view_cat_res/$', views.view_cat_res),
    re_path(r'^remove_user/$', views.del_user),
    re_path(r'^remove_cat/$', views.del_cat),
    re_path(r'^exam_del/$', views.exam_del),
    re_path(r'^send_cred/$', views.send_cred),
    re_path(r'^sent_cred/$', views.sent_cred),
    re_path(r'^get_questions/$', views.get_questions),
    re_path(r'^list_code_questions/$', views.list_code_questions),
    re_path(r'^get_select_que_count/$', views.get_select_que_count),
    re_path(r'^remove_questions/$', views.del_questions),
    re_path(r'^remove_code_questions/$', views.del_code_questions),
    re_path(r'^bulk_reg/$', views.bulk_reg),
    re_path(r'^bulk_que/$', views.bulk_que),
    re_path(r'^bulk_code_que/$', views.bulk_code_que),
    re_path(r'^retrive_email_status/$', views.retrive_email_status),
    re_path(r'^cur_email_status/$', views.cur_email_status),
    re_path(r'^email_status_in_db/$', views.email_status_in_db),
    re_path(r'^get_temp_update/$', views.get_temp_update),
    re_path(r'^get_expected_output/$', views.get_expected_output),
    re_path(r'^all_exam_status/$', views.all_exam_status),
    re_path(r'^add_admin/$', views.add_admin),
    re_path(r'^view_admin/$', views.view_admin),
    re_path(r'^remove_admin/$', views.remove_admin),
    re_path(r'^update_admin/$', views.update_admin),
    re_path(r'^video_stream/$', views.video_stream),
    re_path(r'^server_status/$', views.server_test),
    re_path(r'^log/$', views.log_request),
    re_path(r'^test_code_exe/$', views.test_code_exe),
    re_path(r'^rebuild_que/$', views.rebuild_que),
    ]